# Site settings
title: Apache SAMOA
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samoa.incubator.apache.org" # the base hostname & protocol for your site
twitter_username: ApacheSAMOA 
github_username:  apache/incubator-samoa

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]


